# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0582bd7033b984ac0472421abbf83ee516f0b534a5d8f420f2f680b990d6584c1a674acb4dd510748fbb97ca0cee423e1fb25610c7c160b7612b0807df4009a

test:
  secret_key_base: fa3731a1928a727a28018ad623c62b1ed654aa05b8d824579c9acbc250f6a727a555bcd53ffb4fc2767d3ea6665efb606da64752450b637b0a54e780334a60c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
